import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { PageIntro } from "@/components/public/page-intro";
import { JoinBanner } from "@/components/public/join-banner";
import { society } from "@/lib/public-content";

export const metadata: Metadata = { title: "About", description: "Meet Imperial’s Economics, Finance & Data Science Society: a student community at the intersection of three disciplines." };
export default function AboutPage() {
  return <main id="main-content"><PageIntro eyebrow="About the society" title={<>Different disciplines.<br /><em>Common ground.</em></>} description="A student community for the connections between economics, finance and data science — and the people making them at Imperial." />
    <section className="section"><div className="container editorial-grid"><div><div className="eyebrow">Our starting point</div><h2>The world doesn’t<br />think in subjects.</h2></div><div className="editorial-copy"><p><strong>EFDS stands for Economics, Finance &amp; Data Science Society.</strong> We are the departmental society for students on Imperial Business School’s Economics, Finance and Data Science programme.</p><p>Our community brings different interests to the same table: how economies work, how capital moves and what data can tell us. Society life is a chance to follow those interests beyond the lecture theatre, and build connections along the way.</p><p>Students enrolled on the programme automatically become members, as described by Imperial College Union. For current membership information and other ways to get involved, visit the <a className="text-link" href={society.unionUrl} target="_blank" rel="noreferrer">official EFDS listing <ArrowUpRight size={14} /></a>.</p></div></div></section>
    <section className="section section-tinted"><div className="container"><div className="section-heading"><div><div className="eyebrow">The way we think</div><h2>Curiosity, with <em>company.</em></h2></div></div><div className="feature-grid">{[["01", "Ask better questions", "Look beyond the first answer. Bring a different discipline, a new dataset or a fresh perspective to the conversation."], ["02", "Make room for people", "University is shaped by the people you meet. Share what you know, listen carefully and make the room more welcoming."], ["03", "Put ideas to work", "Explore the connection between theory and practice, whether your next step is a project, a research question or a career."]].map(([n, title, text]) => <article className="feature-card" key={n}><span className="feature-card-number">{n} /</span><h3>{title}</h3><p>{text}</p></article>)}</div><Link className="text-link" style={{ marginTop: 26 }} href="/committee">Meet your committee <ArrowUpRight size={16} /></Link></div></section>
    <section className="section-tight"><div className="container"><p className="editorial-note">EFDS Society is a student society at Imperial College London. This website is operated by the society and is not the official Imperial College London website.</p></div></section><JoinBanner />
  </main>;
}
