import Link from "next/link";
import { KnowledgeAdminNav, ReviewTable, StatusBadge, formatDate } from "@/components/knowledge/operations";
import type { KnowledgeReviewItem } from "@/types/domain";

export function RegisterHeader({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) { return <><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="app-subtitle">{intro}</p><KnowledgeAdminNav /></>; }

export function KnowledgeRegister({ type, eyebrow, title, intro, items }: { type: "requirement" | "timing_rule" | "process" | "resource" | "contact"; eyebrow: string; title: string; intro: string; items: KnowledgeReviewItem[] }) {
  return <div className="app-content"><RegisterHeader eyebrow={eyebrow} title={title} intro={intro} /><div className="ops-inline" style={{ justifyContent: "space-between", marginBottom: 10 }}><span className="muted" style={{ fontSize: 12 }}>{items.length} current record(s)</span><Link className="button button-quiet" href={`/admin/knowledge/review?type=${type}`}>Open filtered review queue</Link></div>{type === "timing_rule" ? <TimingRegister items={items} /> : <ReviewTable items={items} />}</div>;
}

function TimingRegister({ items }: { items: KnowledgeReviewItem[] }) { return <div className="surface" style={{ overflowX: "auto" }}><table className="ops-table"><thead><tr><th>Rule</th><th>Representation</th><th>Source / evidence</th><th>Roles</th><th>Review</th><th>Confidence</th></tr></thead><tbody>{items.map((item) => { const raw = item.raw; const kind = String(raw.deadline_type ?? "unspecified"); const representation = raw.absolute_date ? String(raw.absolute_date) : raw.notice_period_value ? `${String(raw.notice_period_value)} ${String(raw.notice_period_unit ?? "days")}${raw.working_days ? " · working days" : ""}` : String(raw.recurrence_rule ?? raw.relative_to_event_type ?? "No absolute conversion"); return <tr key={item.id}><td><Link href={`/admin/knowledge/review/timing_rule/${item.id}`}><strong>{item.normalizedText}</strong></Link><small>{kind}</small></td><td>{representation}<small>{raw.relative_to_event_type ? `Anchor: ${String(raw.relative_to_event_type)}` : ""}</small></td><td><Link href={`/admin/knowledge/articles/${item.source.articleId}`}>{item.source.title}</Link><small className="ops-evidence">{item.evidenceText}</small></td><td>{item.roleLabels.length ? item.roleLabels.join(", ") : "General"}</td><td><StatusBadge status={item.reviewStatus} stale={item.isStale} /></td><td>{item.confidence === null ? "—" : `${Math.round(item.confidence * 100)}%`}<small>{formatDate(item.reviewedAt)}</small></td></tr>; })}</tbody></table>{!items.length && <div className="empty-state"><h2>No timing rules.</h2></div>}</div>; }
