import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { PageIntro } from "@/components/public/page-intro";
export const metadata: Metadata = { title: "Partners", description: "Start a conversation with EFDS about meaningful student engagement and collaboration." };
export default function PartnersPage() {
  return <main id="main-content"><PageIntro eyebrow="Work with EFDS" title={<>Bring a perspective.<br /><em>Start a conversation.</em></>} description="Connect with students thinking across economics, finance and data science. We welcome conversations about thoughtful, useful collaboration." graphic="finance"><Link className="button button-primary" href="/contact">Discuss a collaboration <ArrowUpRight size={16} /></Link></PageIntro>
    <section className="section"><div className="container"><div className="section-heading"><div><div className="eyebrow">Ideas for working together</div><h2>Something useful.<br /><em>For both sides.</em></h2></div><p>Every collaboration starts with a conversation about the students, the idea and what makes it worthwhile.</p></div><div className="feature-grid">{[["01", "Share your experience", "Bring a practitioner's perspective to a discussion, introduce an unfamiliar field or explain the decisions behind your work."], ["02", "Open up a problem", "Explore a workshop or challenge that gives students the chance to work with an interesting question and practical evidence."], ["03", "Support the community", "Discuss ways to contribute to student development, society activities or the exchange of ideas across disciplines."]].map(([n,title,text]) => <article className="feature-card" key={n}><span className="feature-card-number">{n} /</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section section-tinted"><div className="container editorial-grid"><div><div className="eyebrow">Let’s make it specific</div><h2>What would you<br />like to explore?</h2></div><div className="editorial-copy"><p>Tell the committee who you are, the idea you have in mind, your preferred timing and what students would take away from it.</p><p>All arrangements are subject to discussion with the society and the relevant Imperial College Union processes.</p><Link className="button button-dark" href="/contact">Find the right contact route <ArrowUpRight size={16} /></Link></div></div></section>
  </main>;
}
