import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { getKnowledgeTaxonomyOptions, getProcessDetail } from "@/lib/db/knowledge-ops";
import { reviewKnowledgeAction } from "@/lib/actions/knowledge-review";
import { formatDate, KnowledgeAdminNav, ReviewDetailActions, SourceEvidence, StatusBadge } from "@/components/knowledge/operations";
import { ProcessResourceLinkForm, RichKnowledgeEditForm } from "@/components/knowledge/editing";

export default async function ProcessDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const result = await getProcessDetail(id);
  if (!result) return <div className="app-content"><Link className="button button-quiet" href="/admin/knowledge/processes"><ArrowLeft size={14} /> Back to processes</Link><h1>Process not found</h1></div>;
  const options = await getKnowledgeTaxonomyOptions();
  const { item } = result;
  return <div className="app-content"><Link className="button button-quiet" href="/admin/knowledge/processes"><ArrowLeft size={14} /> Back to processes</Link><div style={{ marginTop: 22 }}><KnowledgeAdminNav /><div className="eyebrow">Process library</div><div className="ops-inline" style={{ justifyContent: "space-between", alignItems: "start" }}><div><h1>{item.normalizedText}</h1><p className="app-subtitle">{item.secondaryText ?? "Source-linked reusable process"}</p></div><StatusBadge status={item.reviewStatus} stale={item.isStale} /></div>
    <RichKnowledgeEditForm item={item} topics={options.topics} roles={options.roles} />
    <SourceEvidence item={item} />
    <section className="surface info-card" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Numbered steps</h2><span className="muted">{result.steps.length}</span></div>{result.steps.map((step) => <div className="queue-row" key={step.id}><div style={{ flex: 1 }}><span className="list-card-meta">Step {String(step.raw.step_number ?? "?")}</span><h3>{step.normalizedText}</h3><p>{step.secondaryText ?? step.evidenceText}</p><RichKnowledgeEditForm item={step} /><form action={reviewKnowledgeAction} style={{ marginTop: 8 }}><input type="hidden" name="action" value="remove_process_step" /><input type="hidden" name="knowledgeType" value="process_step" /><input type="hidden" name="recordId" value={step.id} /><input type="hidden" name="expectedVersion" value={step.reviewVersion} /><button className="button button-quiet" type="submit">Remove from current interpretation</button></form></div><StatusBadge status={step.reviewStatus} stale={step.isStale} /></div>)}{!result.steps.length && <p className="muted">No numbered steps were extracted for this process.</p>}<form action={reviewKnowledgeAction} className="surface info-card" style={{ marginTop: 14 }}><h3>Add normalized step</h3><input type="hidden" name="action" value="add_process_step" /><input type="hidden" name="knowledgeType" value="process" /><input type="hidden" name="recordId" value={item.id} /><input type="hidden" name="expectedVersion" value={item.reviewVersion} /><label className="form-label">Title<input className="input" name="title" /></label><label className="form-label">Instruction<textarea className="textarea" name="instruction" rows={3} required /></label><label className="form-label">Condition<input className="input" name="condition" /></label><button className="button button-dark" type="submit">Add step and approve</button><p className="muted">The source provenance is copied from the parent process and marked as reviewer-added; the ICU source remains unchanged.</p></form></section>
    <section className="surface info-card" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Linked resources</h2><span className="muted">{result.resources.length}</span></div>{result.resources.map((resource) => <Link className="queue-row" href={`/admin/knowledge/review/resource/${resource.id}`} key={resource.id}><div><h3>{resource.normalizedText}</h3><p>{resource.secondaryText ?? resource.evidenceText}</p></div><StatusBadge status={resource.reviewStatus} stale={resource.isStale} /></Link>)}{!result.resources.length && <p className="muted">No process-specific resource links were stored.</p>}<div style={{ display: "grid", gap: 8, marginTop: 14 }}><ProcessResourceLinkForm item={item} resources={result.resourceOptions} action="link_resource" />{result.resources.length > 0 && <ProcessResourceLinkForm item={item} resources={result.resources} action="unlink_resource" />}</div></section>
    <ReviewDetailActions item={item} /><section className="surface info-card" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Review history</h2><span className="muted">{result.events.length}</span></div>{result.events.map((event) => <div className="queue-row" key={event.id}><div><h3>{event.action}</h3><p>{formatDate(event.createdAt)} Â· {event.reviewerName ?? "Reviewer"} Â· {event.reason ?? "No reason"}</p>{Object.keys(event.changes).length > 0 && <code>{JSON.stringify(event.changes)}</code>}</div></div>)}</section></div></div>;
}
