import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { PageIntro } from "@/components/public/page-intro";
import { society } from "@/lib/public-content";
export const metadata: Metadata = { title: "Careers", description: "Explore career directions across economics, finance, quantitative research, data and technology." };
const areas = [["Finance", "Markets, capital and the decisions behind them. Explore investment, corporate finance and asset management."], ["Quantitative research", "Probability, programming and financial models. Investigate where analytical thinking meets markets."], ["Economics & policy", "From incentives to institutions. Explore research and decisions that shape economies and society."], ["Data & AI", "Turn difficult questions into testable ideas through statistics, modelling and responsible use of data."], ["Consulting", "Structure an unfamiliar problem, communicate the evidence and help people make a decision."], ["Software & technology", "Build tools, systems and products that turn technical insight into something people can use."]];
export default function CareersPage() {
  return <main id="main-content"><PageIntro eyebrow="Careers & possibilities" title={<>Your interests.<br /><em>Your next direction.</em></>} description="There is more than one way to put your degree to work. Explore the possibilities, build your understanding and find a direction that feels like yours." graphic="finance"><a className="button button-primary" href={society.careersUrl} target="_blank" rel="noreferrer">Imperial Careers Service <ArrowUpRight size={16} /></a><Link className="button button-outline" href="#career-areas">Explore the fields</Link></PageIntro>
    <section className="section" id="career-areas"><div className="container"><div className="section-heading"><div><div className="eyebrow">Six places to start</div><h2>Follow your <em>curiosity.</em></h2></div><p>These are areas to explore. Imperial’s Careers Service offers current guidance, appointments and opportunities.</p></div><div className="career-list">{areas.map(([title,text], index) => <a className="career-row" href={society.careersUrl} target="_blank" rel="noreferrer" key={title} aria-label={`Explore ${title} with Imperial Careers Service`}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><ArrowUpRight size={20} /></a>)}</div></div></section>
    <section className="section section-tinted"><div className="container editorial-grid"><div><div className="eyebrow">A practical next step</div><h2>Start with a question.<br />Make space for an answer.</h2></div><div className="editorial-copy"><p>What kind of problems do you enjoy? Which skills would you like to use more? A useful career plan starts with understanding yourself, as well as the options.</p><p>Use Imperial’s careers support to explore roles and prepare applications. Society resources and conversations can add another perspective.</p><Link className="button button-dark" href="/resources">Find useful resources <ArrowUpRight size={16} /></Link></div></div></section>
  </main>;
}
