import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { PageIntro } from "@/components/public/page-intro";
import { society } from "@/lib/public-content";
export const metadata: Metadata = { title: "Careers", description: "Explore career directions across economics, finance, quantitative research, data and technology." };
const areas = [["Finance", "Markets, capital and the decisions behind them. Explore investment, corporate finance and asset management."], ["Quantitative research", "Probability, programming and financial models. Investigate where analytical thinking meets markets."], ["Economics & policy", "From incentives to institutions. Explore research and decisions that shape economies and society."], ["Data & AI", "Turn difficult questions into testable ideas through statistics, modelling and responsible use of data."], ["Consulting", "Structure an unfamiliar problem, communicate the evidence and help people make a decision."], ["Software & technology", "Build tools, systems and products that turn technical insight into something people can use."]];
export default function CareersPage() {
  return <main id="main-content"><PageIntro eyebrow="Careers" title="Careers." description="Economics, finance and data science open up several directions. Use this as a starting point, then go to Imperial’s Careers Service for current opportunities and individual support."><a className="button button-primary" href={society.careersUrl} target="_blank" rel="noreferrer">Imperial Careers Service <ArrowUpRight size={16} /></a></PageIntro>
    <section className="section" id="career-areas"><div className="container"><div className="section-heading"><div><span className="editorial-label">Fields to explore</span><h2>Where could the degree take you?</h2></div><p>Each link opens Imperial’s Careers Service, where you can explore roles, find events and book support.</p></div><div className="career-list">{areas.map(([title,text], index) => <a className="career-row" href={society.careersUrl} target="_blank" rel="noreferrer" key={title} aria-label={`Explore ${title} with Imperial Careers Service`}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><ArrowUpRight size={20} /></a>)}</div></div></section>
    <section className="section section-tinted"><div className="container editorial-grid"><div><span className="editorial-label">Before you apply</span><h2>Use the support<br />available to you.</h2></div><div className="editorial-copy"><p>For guidance on applications, interviews and choosing a direction, start with Imperial’s careers support. Check the employer’s own listing for deadlines and eligibility.</p><p>The society’s public resources are collected in our directory. Signed-in members can also explore the opportunities available in their workspace.</p><Link className="text-link" href="/resources">Open the resource directory <ArrowUpRight size={16} /></Link></div></div></section>
  </main>;
}
