import Link from "next/link";
import { FileText, Search } from "lucide-react";
import type { DocumentArchiveItem } from "@/types/domain";

function date(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value)) : "—"; }

export function DocumentNav() { return <nav className="tag-list" aria-label="Document archive navigation" style={{ marginBottom: 24 }}><Link className="tag" href="/admin/documents">Overview</Link><Link className="tag" href="/admin/documents/files">Files and search</Link></nav>; }

export function DocumentTable({ items }: { items: DocumentArchiveItem[] }) {
  return <div className="surface" style={{ overflowX: "auto" }}><table className="ops-table"><thead><tr><th>File</th><th>Area</th><th>Status</th><th>Extraction</th><th>Modified</th><th>Duplicates</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link href={`/admin/documents/files/${item.id}`}><strong>{item.title}</strong></Link><small>{item.relativePath || "No relative path"}</small></td><td>{item.sourceArea || "—"}</td><td>{item.isMissing ? <span className="badge badge-neutral">missing</span> : item.isUnavailable ? <span className="badge badge-coral">unavailable</span> : <span className="badge badge-mint">current</span>}</td><td>{item.extractionStatus || "pending"}{item.extractionError && <small>{item.extractionError}</small>}</td><td>{date(item.filesystemModifiedAt)}</td><td>{item.duplicateCount > 1 ? <span className="badge badge-coral">{item.duplicateCount} copies</span> : "—"}</td></tr>)}</tbody></table>{!items.length && <div className="empty-state"><FileText size={22} /><h2>No filesystem documents found.</h2><p>Run the backend filesystem synchronizer after applying its migration.</p></div>}</div>;
}

export function DocumentSearchForm({ query = "", area = "", status = "", extraction = "", extension = "", from = "", to = "", duplicate = false, areas = [] }: { query?: string; area?: string; status?: string; extraction?: string; extension?: string; from?: string; to?: string; duplicate?: boolean; areas?: string[] }) {
  return <form className="ops-inline" method="get" action="/admin/documents/files" style={{ margin: "18px 0", alignItems: "end", flexWrap: "wrap" }}><label className="form-label" style={{ flex: "1 1 260px" }}>Search files and extracted text<input className="input" name="q" defaultValue={query} placeholder="Filename, path or text…" /></label><label className="form-label">Area<select className="input" name="area" defaultValue={area}><option value="">All areas</option>{areas.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="form-label">Extension<input className="input" name="extension" defaultValue={extension} placeholder=".pdf" /></label><label className="form-label">Status<select className="input" name="status" defaultValue={status}><option value="">All statuses</option><option value="current">Current</option><option value="missing">Missing</option><option value="unavailable">Unavailable</option></select></label><label className="form-label">Extraction<select className="input" name="extraction" defaultValue={extraction}><option value="">All extraction states</option><option value="extracted">Extracted</option><option value="unsupported">Unsupported</option><option value="failed">Failed</option><option value="unavailable">Unavailable</option></select></label><label className="form-label">Modified from<input className="input" type="date" name="from" defaultValue={from} /></label><label className="form-label">Modified to<input className="input" type="date" name="to" defaultValue={to} /></label><label className="tag"><input type="checkbox" name="duplicate" value="true" defaultChecked={duplicate} /> duplicates</label><button className="button button-dark" type="submit"><Search size={14} /> Search</button></form>;
}

export function DocumentChangeList({ changes }: { changes: { id: string; changeType: string; previousPath: string | null; newPath: string | null; detectedAt: string | null }[] }) { return <div>{changes.map((change) => <div className="queue-row" key={change.id}><div><strong>{change.changeType}</strong><p>{change.previousPath || "—"} → {change.newPath || "—"}</p></div><small>{date(change.detectedAt)}</small></div>)}</div>; }

export function DocumentVersionList({ versions }: { versions: { id: string; contentHash: string; extractionStatus: string; ingestedAt: string | null; fileSizeBytes: number | null }[] }) { return <div>{versions.map((version) => <div className="queue-row" key={version.id}><div><strong>{version.extractionStatus}</strong><p><code>{version.contentHash}</code></p></div><small>{date(version.ingestedAt)}{version.fileSizeBytes !== null ? ` · ${version.fileSizeBytes} bytes` : ""}</small></div>)}</div>; }
