import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { getDocumentDashboard } from "@/lib/db/documents";
import { DocumentNav } from "@/components/documents/archive";

export default async function AdminDocumentsPage() {
  const dashboard = await getDocumentDashboard();
  return <div className="app-content"><div className="eyebrow">Admin · OneDrive filesystem archive</div><h1>The institutional<br />file shelf.</h1><p className="app-subtitle">A private, source-preserving archive of the EFDS OneDrive tree. Files remain internal until a future explicit publication decision.</p><DocumentNav /><div className="metric-grid"><Metric label="Source files" value={dashboard.counts.files} /><Metric label="Current" value={dashboard.counts.current} /><Metric label="Versions" value={dashboard.counts.versions} /><Metric label="Missing" value={dashboard.counts.missing} /><Metric label="Duplicates" value={dashboard.counts.duplicates} /><Metric label="Failures" value={dashboard.counts.failures + dashboard.counts.unavailable} /></div><div className="app-grid" style={{ marginTop: 24 }}><section className="surface app-panel"><div className="panel-heading"><h2>Filesystem health</h2><Link href="/admin/documents/files">Browse files <ArrowRight size={12} /></Link></div><dl className="security-details"><div><dt>Latest sync</dt><dd>{String(dashboard.latestRun?.status ?? "Not run")}</dd></div><div><dt>Discovered</dt><dd>{dashboard.latestRun?.records_seen ?? 0}</dd></div><div><dt>Changed</dt><dd>{dashboard.latestRun?.records_updated ?? 0}</dd></div><div><dt>Errors</dt><dd>{dashboard.latestRun?.records_failed ?? 0}</dd></div></dl></section><aside className="surface-dark app-panel"><div className="eyebrow" style={{ color: "var(--mint)" }}>Source boundary</div><h2 style={{ color: "var(--paper)", marginTop: 26, fontSize: 20, fontWeight: 500 }}>Admin-only raw files.</h2><p style={{ color: "rgba(247,247,243,.68)", fontSize: 12, lineHeight: 1.5 }}>Repository folders, credentials, temporary files and cloud-only unreadable files are excluded or marked without exposing their contents.</p></aside></div><section style={{ marginTop: 24 }}><div className="eyebrow">Recent source changes</div><div className="surface info-card">{dashboard.recentChanges.map((change) => <div className="queue-row" key={change.id}><div><strong>{change.changeType}</strong><p>{change.previousPath || "—"} → {change.newPath || "—"}</p></div><small>{change.detectedAt || "—"}</small></div>)}{!dashboard.recentChanges.length && <p className="muted">No source changes recorded yet.</p>}</div></section><p className="muted" style={{ fontSize: 11, marginTop: 16 }}>Areas discovered from the current filesystem archive: {dashboard.areas.join(", ") || "none yet"}.</p></div>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="metric surface"><span>{label}</span><strong>{value}</strong><small>live database value</small></div>; }
