import Link from "next/link";
import { OperationsNav } from "@/components/operations/archive";
import { getOperationsDashboard } from "@/lib/db/operations";

export default async function OperationsPage() {
  const dashboard = await getOperationsDashboard();
  return <div className="app-content"><div className="eyebrow">Admin · operational truth</div><h1>Keep the important<br />work honest.</h1><p className="app-subtitle">Candidate decisions, actions, commitments, questions and updates become operational truth only after an explicit human review.</p><OperationsNav /><div className="metric-grid"><Metric label="Needs review" value={dashboard.counts.needsReview} href="/admin/operations?review=needs_review" /><Metric label="Open actions" value={dashboard.counts.openActions} href="/admin/operations/actions?execution=open" /><Metric label="Overdue" value={dashboard.counts.overdue} href="/admin/operations/actions?overdue=true" /><Metric label="Blocked" value={dashboard.counts.blocked} href="/admin/operations/actions?execution=blocked" /><Metric label="Decisions" value={dashboard.counts.decisions} href="/admin/operations/decisions" /><Metric label="Questions" value={dashboard.counts.questions} href="/admin/operations/questions" /></div><div className="app-grid" style={{ marginTop: 24 }}><section className="surface app-panel"><div className="panel-heading"><h2>Recent operational records</h2><Link href="/admin/operations/new">Create candidate</Link></div>{dashboard.recent.map((item) => <div className="queue-row" key={item.id}><div><Link href={`/admin/operations/${item.id}`}><strong>{item.title}</strong></Link><small>{item.recordType.replaceAll("_", " ")} · {item.reviewStatus.replaceAll("_", " ")}</small></div><small>{item.workstream || "Unclassified"}</small></div>)}{!dashboard.recent.length && <p className="muted">No operational records yet.</p>}</section><aside className="surface-dark app-panel"><div className="eyebrow" style={{ color: "var(--mint)" }}>Evidence boundary</div><h2 style={{ color: "var(--paper)", marginTop: 26, fontSize: 20, fontWeight: 500 }}>Interpretation is not source.</h2><p style={{ color: "rgba(247,247,243,.68)", fontSize: 12, lineHeight: 1.5 }}>Slack, transcripts, documents and Meetily summaries remain evidence. This register stores reviewed interpretations and keeps their source references attached.</p></aside></div><section style={{ marginTop: 24 }}><div className="panel-heading"><h2>Recent review activity</h2><Link href="/admin/operations/timeline">Open timeline</Link></div><div className="surface">{dashboard.latestEvents.map((event) => <div className="queue-row" key={event.id}><div><strong>{event.action.replaceAll("_", " ")}</strong><small>{event.previousReviewStatus || "—"} → {event.newReviewStatus || "—"}</small></div><small>{event.reason || "No reason recorded"}</small></div>)}{!dashboard.latestEvents.length && <p className="muted">No review activity yet.</p>}</div></section></div>;
}

function Metric({ label, value, href }: { label: string; value: number; href: string }) { return <Link className="metric surface" href={href}><span>{label}</span><strong>{value}</strong><small>live database value</small></Link>; }
