import Link from "next/link";
import { getCommitteeDirectory } from "@/lib/db/committee";

export default async function AdminCommitteePage() {
  const { officers, unlinked, recentMembers } = await getCommitteeDirectory();
  const linked = officers.filter((officer) => officer.profileEmail).length;
  return <div className="app-content committee-admin-page">
    <div className="eyebrow">Admin · committee identity</div>
    <h1>People behind<br />the work.</h1>
    <p className="app-subtitle">Check which signed-in account is connected to each active officer entry. Committee access and roster identity are separate steps.</p>
    <Link className="button button-dark" href="/admin/accounts">Review accounts and assign roles</Link>
    <section className="ticket-metrics" aria-label="Committee account status"><div><span>Active officers</span><strong>{officers.length}</strong><small>Roster entries</small></div><div><span>Linked accounts</span><strong>{linked}</strong><small>Ready for assigned tickets</small></div><div><span>Awaiting a link</span><strong>{officers.length - linked}</strong><small>Officer entries without an account</small></div><div><span>Access without a role</span><strong>{unlinked.length}</strong><small>Committee/admin accounts</small></div></section>
    <section className="committee-directory" aria-label="Active officer roster"><div className="panel-heading"><h2>Officer roster and account links</h2><span>{officers.length} active</span></div>{officers.length ? <div className="committee-directory-grid">{officers.map((officer) => <article className="surface committee-directory-card" key={officer.id}><div><span className="eyebrow">{officer.academicYear}</span><h3>{officer.name}</h3><p>{officer.role}</p></div><div className="committee-directory-link"><span className={`badge ${officer.profileEmail ? "badge-mint" : "badge-neutral"}`}>{officer.profileEmail ? "Linked" : "No account linked"}</span>{officer.profileEmail && <small>{officer.profileEmail}</small>}</div></article>)}</div> : <div className="surface empty-state"><h2>No active officer entries.</h2><p>The knowledge-base roster has no active officers in this workspace.</p></div>}</section>
    <div className="committee-directory-bottom"><section className="surface app-panel"><h2>Committee access, no roster link</h2><p>These accounts can access committee tools, but their officer identity is not connected.</p>{unlinked.map((profile) => <div className="queue-row" key={profile.email}><div><strong>{profile.fullName || profile.email}</strong><small>{profile.email}</small></div><span className="badge badge-neutral">{profile.role}</span></div>)}{!unlinked.length && <p className="muted">No committee accounts are missing a roster link.</p>}</section><section className="surface app-panel"><h2>Recent member accounts</h2><p>First sign-in creates a member account. Verify EFDS membership, then grant committee access and link the roster entry.</p>{recentMembers.map((profile) => <div className="queue-row" key={profile.email}><div><strong>{profile.fullName || profile.email}</strong><small>{profile.email}</small></div><span className="badge badge-neutral">{profile.role === "efds_member" ? "EFDS member" : "Member"}</span></div>)}{!recentMembers.length && <p className="muted">No member accounts have signed in yet.</p>}</section></div>
  </div>;
}
