import Link from "next/link";
import { ReviewTable, KnowledgeAdminNav } from "@/components/knowledge/operations";
import { getKnowledgeFilterOptions, listReviewQueue } from "@/lib/db/knowledge-ops";

type Params = Record<string, string | string[] | undefined>;
function one(params: Params, key: string) { const value = params[key]; return Array.isArray(value) ? value[0] : value; }

export default async function ReviewQueuePage({ searchParams }: { searchParams: Promise<Params> }) {
  const params = await searchParams;
  const filters = { type: one(params, "type"), status: one(params, "status"), stale: one(params, "stale"), topic: one(params, "topic"), role: one(params, "role"), source: one(params, "source"), method: one(params, "method"), confidence: one(params, "confidence"), q: one(params, "q"), sort: one(params, "sort"), page: Number(one(params, "page") ?? 1) };
  const [{ items, total, page, pageSize }, options] = await Promise.all([listReviewQueue(filters), getKnowledgeFilterOptions()]);
  const query = new URLSearchParams(Object.entries(params).flatMap(([key, value]) => value === undefined ? [] : [[key, Array.isArray(value) ? value[0] : value]]));
  const previous = new URLSearchParams(query); previous.set("page", String(Math.max(1, page - 1)));
  const next = new URLSearchParams(query); next.set("page", String(page + 1));
  return <div className="app-content"><div className="eyebrow">Admin · unified review</div><h1>Review the<br />operating signal.</h1><p className="app-subtitle">Every candidate keeps its source evidence, extraction metadata and version state visible before it becomes trusted EFDS knowledge.</p><KnowledgeAdminNav />
    <form className="surface info-card ops-filter" method="get"><label>Search<input name="q" defaultValue={filters.q} placeholder="Text, source or evidence" /></label><label>Type<select name="type" defaultValue={filters.type ?? ""}><option value="">All types</option><option value="requirement">Requirements</option><option value="timing_rule">Timing</option><option value="process">Processes</option><option value="process_step">Process steps</option><option value="resource">Resources</option><option value="contact">Contacts</option></select></label><label>Status<select name="status" defaultValue={filters.status ?? ""}><option value="">All statuses</option><option value="proposed">Proposed</option><option value="needs_review">Needs review</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="superseded">Superseded</option></select></label><label>Freshness<select name="stale" defaultValue={filters.stale ?? ""}><option value="">Current and stale</option><option value="stale">Stale first</option><option value="current">Current only</option></select></label><label>Topic<select name="topic" defaultValue={filters.topic ?? ""}><option value="">All topics</option>{options.topics.map((topic) => <option key={topic}>{topic}</option>)}</select></label><label>Role<select name="role" defaultValue={filters.role ?? ""}><option value="">All roles</option>{options.roles.map((role) => <option key={role}>{role}</option>)}</select></label><label>Source<select name="source" defaultValue={filters.source ?? ""}><option value="">All source articles</option>{options.sources.map(([id, title]) => <option value={id} key={id}>{title}</option>)}</select></label><label>Method<select name="method" defaultValue={filters.method ?? ""}><option value="">All methods</option>{options.methods.map((method) => <option key={method}>{method}</option>)}</select></label><label>Confidence<select name="confidence" defaultValue={filters.confidence ?? ""}><option value="">Any confidence</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Sort<select name="sort" defaultValue={filters.sort ?? "priority"}><option value="priority">Priority</option><option value="stale">Stale first</option><option value="newest">Newest extraction</option><option value="confidence">Lowest confidence</option><option value="source_changed">Source changed</option></select></label><button className="button button-dark" type="submit">Apply filters</button></form>
    <div className="ops-inline" style={{ justifyContent: "space-between", margin: "18px 0 10px" }}><span className="muted" style={{ fontSize: 12 }}>{total} matching record(s)</span><span className="muted" style={{ fontSize: 12 }}>Page {page} · {pageSize} per page</span></div><ReviewTable items={items} bulkActions />
    {total > pageSize && <div className="ops-inline" style={{ justifyContent: "space-between", marginTop: 16 }}><span>{page > 1 && <Link className="button button-quiet" href={`/admin/knowledge/review?${previous}`}>Previous</Link>}</span><span>{page * pageSize < total && <Link className="button button-quiet" href={`/admin/knowledge/review?${next}`}>Next</Link>}</span></div>}
  </div>;
}
