import type { Metadata } from "next";
import Link from "next/link";
import { InformationCard, InformationPage } from "../../../components/public/information-page";

export const metadata: Metadata = { title: "Privacy", description: "How EFDS Society uses account, profile and operational information." };

export default function PrivacyPage() {
  return <InformationPage eyebrow="Privacy" title="Privacy." intro="This page describes the information used by the EFDS website and its Supabase-backed member workspace, based on the current application and backend schema.">
    <InformationCard eyebrow="Who operates this site" title="EFDS Society is a student society site."><p>EFDS Society is a student society at Imperial College London. This website is operated by the society and is not the official Imperial College London website.</p><p>For a question about information held about your account, correction, deletion where applicable, or a privacy concern, please use the <Link href="/contact">contact route</Link>.</p></InformationCard>
    <InformationCard eyebrow="Account information" title="What the current application uses"><p>When you authenticate, EFDS uses the Supabase Auth identity supplied by the configured provider. The application reads the authenticated user ID, email address, email-confirmation status, and available name metadata for sign-in and profile provisioning.</p><ul><li><strong>Profile:</strong> email, optional full name, member type, access role, optional officer association, active state, login timestamp, row timestamps, and profile metadata.</li><li><strong>Identity link:</strong> the Supabase Auth user ID linking an authenticated account to its EFDS profile.</li><li><strong>External access:</strong> approved non-Imperial exceptions may contain an email, access role, optional member type, reason, active state, expiry, creator profile reference, timestamps, and metadata.</li></ul><p>The website does not treat a client-provided role or email as authoritative. EFDS authorization is resolved server-side.</p></InformationCard>
    <InformationCard eyebrow="Authentication" title="Email first, with optional Google sign-in"><p>Imperial users can sign in with a verified <code>ic.ac.uk</code> or <code>imperial.ac.uk</code> email address and password or a secure email link. Google sign-in is available when its OAuth provider is configured. Both paths use Supabase Auth; EFDS then checks the authenticated email domain and the EFDS profile.</p><p>Approved external users may also use the email flow. Authentication establishes identity; it does not automatically grant a committee or admin role.</p></InformationCard>
    <InformationCard eyebrow="Provider data" title="Identity only"><p>Google sign-in uses basic OpenID Connect identity information and does not request Gmail, Drive or Calendar access. Website sign-in does not call Microsoft Graph or request mailbox, file or calendar permissions.</p></InformationCard>
    <InformationCard eyebrow="Services" title="What Supabase and Vercel do"><ul><li><strong>Supabase Auth:</strong> handles the configured authentication flows and session lifecycle.</li><li><strong>Supabase PostgreSQL:</strong> stores the application profile/access model and backend knowledge/operational records, with RLS policies defined by the backend migration.</li><li><strong>Vercel:</strong> hosts and deploys the Next.js website. It is not the EFDS database or identity provider.</li></ul></InformationCard>
    <InformationCard eyebrow="Operational information" title="Current scope of the backend"><p>The backend schema includes officers, profiles, approved access exceptions, knowledge articles and derived knowledge records, documents, meetings, decisions, action items, and Slack records. These are subject to the application’s private role boundaries and database RLS.</p><p>The job tracker currently rendered by the website is static page data; this audit found no demonstrated user-specific persistence for saved jobs. This notice does not claim that every backend table is populated or written by the current website.</p></InformationCard>
    <InformationCard eyebrow="Cookies and sessions" title="Authentication needs a session"><p>The Next.js application uses Supabase’s SSR client to read and update authentication session cookies. These cookies support sign-in, server-side identity checks, and session continuity. The application callback exchanges the authorization code server-side before evaluating EFDS access.</p></InformationCard>
    <InformationCard eyebrow="Retention and requests" title="Questions are welcome"><p>No formal published retention schedule is defined in the current repositories. The operational approach is to retain account, authorization, and operational records for as long as needed to run and secure the society service, and to review requests for correction or deletion against account, access, audit, and operational needs.</p><p>To ask what account information is held, request correction, request deletion where applicable, or raise a privacy concern, use <Link href="/contact">/contact</Link>. Please do not send passwords, access tokens, or other secrets.</p></InformationCard>
  </InformationPage>;
}
