import type { Metadata } from "next";
import Link from "next/link";
import { InformationCard, InformationPage } from "../../../components/public/information-page";

export const metadata: Metadata = { title: "Privacy", description: "How EFDS Society uses account, profile and operational information." };

export default function PrivacyPage() {
  return <InformationPage eyebrow="Privacy" title="A clear account of your data." intro="This page describes the information used by the EFDS website and its Supabase-backed member workspace, based on the current application and backend schema.">
    <InformationCard eyebrow="Who operates this site" title="EFDS Society is a student society site."><p>EFDS Society is a student society at Imperial College London. This website is operated by the society and is not the official Imperial College London website.</p><p>For a question about information held about your account, correction, deletion where applicable, or a privacy concern, please use the <Link href="/contact">contact route</Link>.</p></InformationCard>
    <InformationCard eyebrow="Account information" title="What the current application uses"><p>When you authenticate, EFDS uses the Supabase Auth identity supplied by the configured provider. The application reads the authenticated user ID, email address, email-confirmation status, and available name metadata for sign-in and profile provisioning.</p><ul><li><strong>Profile:</strong> email, optional full name, member type, access role, optional officer association, active state, login timestamp, row timestamps, and profile metadata.</li><li><strong>Identity link:</strong> the Supabase Auth user ID linking an authenticated account to its EFDS profile.</li><li><strong>External access:</strong> approved non-Imperial exceptions may contain an email, access role, optional member type, reason, active state, expiry, creator profile reference, timestamps, and metadata.</li></ul><p>The website does not treat a client-provided role or email as authoritative. EFDS authorization is resolved server-side.</p></InformationCard>
    <InformationCard eyebrow="Authentication" title="Microsoft first, with an external exception path"><p>Imperial users normally authenticate with Microsoft Entra ID through Supabase Auth. The effective OpenID Connect identity scopes are <code>openid profile email</code>. EFDS then independently checks the verified email against the approved Imperial domains <code>ic.ac.uk</code> and <code>imperial.ac.uk</code>.</p><p>Approved external users may use the separate Supabase email magic-link/OTP flow. Authentication only establishes identity; it does not automatically grant an EFDS role.</p></InformationCard>
    <InformationCard eyebrow="Microsoft data" title="Identity only"><p>EFDS does not call the Microsoft Graph API. The current implementation does not request or use access to Microsoft email or mailboxes, calendars, OneDrive, SharePoint, Teams, contacts, Microsoft 365 files, groups, or directory-wide organisation information.</p><p>The Microsoft integration is used for authentication and basic identity claims. It is not used as a Microsoft 365 data integration.</p></InformationCard>
    <InformationCard eyebrow="Services" title="What Supabase and Vercel do"><ul><li><strong>Supabase Auth:</strong> handles the configured authentication flows and session lifecycle.</li><li><strong>Supabase PostgreSQL:</strong> stores the application profile/access model and backend knowledge/operational records, with RLS policies defined by the backend migration.</li><li><strong>Vercel:</strong> hosts and deploys the Next.js website. It is not the EFDS database or identity provider.</li></ul></InformationCard>
    <InformationCard eyebrow="Operational information" title="Current scope of the backend"><p>The backend schema includes officers, profiles, approved access exceptions, knowledge articles and derived knowledge records, documents, meetings, decisions, action items, and Slack records. These are subject to the application’s private role boundaries and database RLS.</p><p>The job tracker currently rendered by the website is static page data; this audit found no demonstrated user-specific persistence for saved jobs. This notice does not claim that every backend table is populated or written by the current website.</p></InformationCard>
    <InformationCard eyebrow="Cookies and sessions" title="Authentication needs a session"><p>The Next.js application uses Supabase’s SSR client to read and update authentication session cookies. These cookies support sign-in, server-side identity checks, and session continuity. The application callback exchanges the authorization code server-side before evaluating EFDS access.</p></InformationCard>
    <InformationCard eyebrow="Retention and requests" title="Questions are welcome"><p>No formal published retention schedule is defined in the current repositories. The operational approach is to retain account, authorization, and operational records for as long as needed to run and secure the society service, and to review requests for correction or deletion against account, access, audit, and operational needs.</p><p>To ask what account information is held, request correction, request deletion where applicable, or raise a privacy concern, use <Link href="/contact">/contact</Link>. Please do not send passwords, access tokens, or other secrets.</p></InformationCard>
  </InformationPage>;
}
