import { Check, CircleHelp, Plus, Search } from "lucide-react";
import Link from "next/link";
import { operationalRecordAction } from "@/lib/actions/operations";
import type { OperationalEvidence, OperationalRecord, OperationalRecordType, OperationalReviewEvent, UnifiedRetrievalResult } from "@/types/domain";

const labels: Record<string, string> = { decision: "Decision", action_item: "Action item", commitment: "Commitment", open_question: "Open question", status_update: "Status update" };
function date(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
function badge(value: string | null) { return value ? <span className="badge badge-neutral">{value.replaceAll("_", " ")}</span> : <span className="muted">—</span>; }

export function OperationsNav() { return <nav className="tag-list" aria-label="Operational records navigation" style={{ marginBottom: 24 }}><Link className="tag" href="/admin/operations">Overview</Link><Link className="tag" href="/admin/operations/decisions">Decisions</Link><Link className="tag" href="/admin/operations/actions">Actions</Link><Link className="tag" href="/admin/operations/questions">Questions</Link><Link className="tag" href="/admin/operations/timeline">Timeline</Link><Link className="tag" href="/admin/operations/new"><Plus size={12} /> New record</Link></nav>; }

export function OperationsTable({ items }: { items: OperationalRecord[] }) {
  return <div className="surface" style={{ overflowX: "auto" }}><table className="ops-table"><thead><tr><th>Record</th><th>Type</th><th>Review</th><th>Execution</th><th>Owner</th><th>Due</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><Link href={`/admin/operations/${item.id}`}><strong>{item.title}</strong></Link><small>{item.workstream || "Unclassified"}</small></td><td>{labels[item.recordType] || item.recordType}</td><td>{badge(item.reviewStatus)}</td><td>{badge(item.executionStatus)}</td><td>{item.ownerText || item.ownerProfileId || item.ownerOfficerId || "Unassigned"}</td><td>{item.dueText || date(item.dueAt)}</td></tr>)}</tbody></table>{!items.length && <div className="empty-state"><CircleHelp size={22} /><h2>No operational records found.</h2><p>Create a proposed record from an evidence source or the new-record form.</p></div>}</div>;
}

export function OperationsFilters({ type, review, execution, workstream, query, overdue, workstreams }: { type?: string; review?: string; execution?: string; workstream?: string; query?: string; overdue?: boolean; workstreams: string[] }) {
  return <form className="ops-inline" method="get" style={{ margin: "18px 0", alignItems: "end", flexWrap: "wrap" }}><label className="form-label" style={{ flex: "1 1 240px" }}>Search<input className="input" name="q" defaultValue={query} placeholder="Title, description or workstream" /></label><label className="form-label">Type<select className="select" name="type" defaultValue={type}><option value="">All types</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="form-label">Review<select className="select" name="review" defaultValue={review}><option value="">All review states</option><option value="proposed">Proposed</option><option value="needs_review">Needs review</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="superseded">Superseded</option></select></label><label className="form-label">Execution<select className="select" name="execution" defaultValue={execution}><option value="">All execution states</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option><option value="resolved">Resolved</option></select></label><label className="form-label">Workstream<select className="select" name="workstream" defaultValue={workstream}><option value="">All workstreams</option>{workstreams.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label className="tag"><input type="checkbox" name="overdue" value="true" defaultChecked={overdue} /> overdue</label><button className="button button-dark" type="submit"><Search size={14} /> Filter</button></form>;
}

export function NewOperationalRecordForm({ defaultType = "decision", evidenceId }: { defaultType?: OperationalRecordType; evidenceId?: string }) {
  return <form action={operationalRecordAction} className="surface info-card"><input type="hidden" name="action" value="create" />{evidenceId && <input type="hidden" name="evidenceId" value={evidenceId} />}<label className="form-label">Type<select className="select" name="recordType" defaultValue={defaultType}><option value="decision">Decision</option><option value="action_item">Action item</option><option value="commitment">Commitment</option><option value="open_question">Open question</option><option value="status_update">Status update</option></select></label><label className="form-label">Title<input className="input" name="title" required maxLength={500} /></label><label className="form-label">Description<textarea className="textarea" name="description" rows={5} /></label><div className="ops-inline"><label className="form-label">Workstream<input className="input" name="workstream" placeholder="events, finance, sponsorship…" /></label><label className="form-label">Owner text<input className="input" name="owner_text" placeholder="Optional external person or team" /></label><label className="form-label">Due text<input className="input" name="due_text" placeholder="Before Freshers' Fair" /></label></div><label className="form-label">Occurred at<input className="input" type="datetime-local" name="occurred_at" /></label>{evidenceId && <input type="hidden" name="patch" value={JSON.stringify({ retrieval_unit_id: evidenceId })} />}<button className="button button-primary" type="submit"><Plus size={14} /> Create proposed record</button></form>;
}

export function RecordActions({ record }: { record: OperationalRecord }) {
  const hidden = <><input type="hidden" name="recordId" value={record.id} /><input type="hidden" name="expectedVersion" value={record.reviewVersion} /></>;
  return <div className="ops-inline" style={{ flexWrap: "wrap", marginTop: 18 }}><form action={operationalRecordAction}><input type="hidden" name="action" value="approve" />{hidden}<button className="button button-primary" type="submit"><Check size={14} /> Approve</button></form><form action={operationalRecordAction}><input type="hidden" name="action" value="defer" />{hidden}<button className="button button-quiet" type="submit">Needs review</button></form><form action={operationalRecordAction}><input type="hidden" name="action" value="reject" />{hidden}<input className="input" name="reason" placeholder="Rejection reason" required /><button className="button button-quiet" type="submit">Reject</button></form>{record.reviewStatus === "approved" && <><form action={operationalRecordAction}><input type="hidden" name="action" value="publish" />{hidden}<select className="select" name="visibility" defaultValue={record.visibility}><option value="committee">Publish committee</option><option value="member">Publish member</option><option value="public">Publish public</option></select><button className="button button-primary" type="submit">Publish</button></form><form action={operationalRecordAction}><input type="hidden" name="action" value="unpublish" />{hidden}<button className="button button-quiet" type="submit">Unpublish</button></form></>}{record.recordType === "action_item" && <form action={operationalRecordAction}><input type="hidden" name="action" value="change_execution_status" />{hidden}<select className="select" name="patch" defaultValue={JSON.stringify({ execution_status: record.executionStatus || "open" })} aria-label="Execution status"><option value={JSON.stringify({ execution_status: "open" })}>Open</option><option value={JSON.stringify({ execution_status: "in_progress" })}>In progress</option><option value={JSON.stringify({ execution_status: "blocked" })}>Blocked</option><option value={JSON.stringify({ execution_status: "completed" })}>Completed</option></select><button className="button button-quiet" type="submit">Update status</button></form>}{record.recordType === "decision" && <form action={operationalRecordAction}><input type="hidden" name="action" value="supersede" />{hidden}<input className="input" name="superseded_by_id" placeholder="Replacement record UUID" required /><button className="button button-quiet" type="submit">Supersede</button></form>}</div>;
}

export function EditOperationalRecordForm({ record }: { record: OperationalRecord }) {
  return <form action={operationalRecordAction} className="surface info-card" style={{ marginTop: 18 }}><input type="hidden" name="action" value="edit_approve" /><input type="hidden" name="recordId" value={record.id} /><input type="hidden" name="expectedVersion" value={record.reviewVersion} /><div className="panel-heading"><h2>Edit and approve</h2><span className="muted">Interpretation only; evidence remains immutable</span></div><label className="form-label">Title<input className="input" name="title" defaultValue={record.title} required /></label><label className="form-label">Description<textarea className="textarea" name="description" defaultValue={record.description || ""} rows={5} /></label><div className="ops-inline"><label className="form-label">Workstream<input className="input" name="workstream" defaultValue={record.workstream || ""} /></label><label className="form-label">Owner<input className="input" name="owner_text" defaultValue={record.ownerText || ""} /></label><label className="form-label">Due text<input className="input" name="due_text" defaultValue={record.dueText || ""} /></label><label className="form-label">Execution status<select className="select" name="execution_status" defaultValue={record.executionStatus || "open"}><option value="open">Open</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="answered">Answered</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></label></div><button className="button button-primary" type="submit">Save interpretation and approve</button></form>;
}

export function EvidenceList({ record, evidence }: { record: OperationalRecord; evidence: OperationalEvidence[] }) { return <section className="surface info-card" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Evidence</h2><span className="muted">Source references, not copied truth</span></div>{evidence.map((item) => <div className="queue-row" key={item.id}><div><strong>{item.title || item.sourceType}</strong><small>{item.sourceType} · {item.evidenceRole} · {item.sourceRecordId}</small>{item.evidenceText && <p className="ops-quote">{item.evidenceText}</p>}</div><form action={operationalRecordAction}><input type="hidden" name="action" value="detach_evidence" /><input type="hidden" name="recordId" value={record.id} /><input type="hidden" name="expectedVersion" value={record.reviewVersion} /><input type="hidden" name="patch" value={JSON.stringify({ evidence_id: item.id })} /><button className="button button-quiet" type="submit">Detach</button></form></div>)}{!evidence.length && <p className="muted">No evidence attached yet.</p>}</section>; }

export function EvidencePicker({ record, results }: { record: OperationalRecord; results: UnifiedRetrievalResult[] }) { return <section className="surface info-card" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Add evidence</h2><span className="muted">Search results are permission-scoped</span></div><form method="get" className="ops-inline"><input type="hidden" name="evidence" value="1" /><input className="input" name="evidenceQuery" placeholder="Search source evidence" /><button className="button button-quiet" type="submit"><Search size={14} /> Search</button></form>{results.map((result) => <div className="queue-row" key={result.retrievalUnitId}><div><strong>{result.title}</strong><small>{result.sourceType} · {result.sourceRecordId}</small><p><span>{result.snippet.replace(/<[^>]*>/g, "")}</span></p></div><form action={operationalRecordAction}><input type="hidden" name="action" value="attach_evidence" /><input type="hidden" name="recordId" value={record.id} /><input type="hidden" name="expectedVersion" value={record.reviewVersion} /><input type="hidden" name="patch" value={JSON.stringify({ retrieval_unit_id: result.retrievalUnitId, evidence_role: "supporting", evidence_text: result.snippet.replace(/<[^>]*>/g, "") })} /><button className="button button-primary" type="submit">Attach</button></form></div>)}</section>; }

export function ReviewTimeline({ events }: { events: OperationalReviewEvent[] }) { return <div className="queue-list">{events.map((event) => <div className="queue-row" key={event.id}><div><strong>{event.action.replaceAll("_", " ")}</strong><small>{event.previousReviewStatus || "—"} → {event.newReviewStatus || "—"}</small>{event.reason && <small>{event.reason}</small>}</div><small>{date(event.createdAt)}</small></div>)}</div>; }
