import Link from "next/link";
import { ArrowLeft, ExternalLink } from "lucide-react";
import { getDocument } from "@/lib/db/documents";
import { DocumentChangeList, DocumentNav, DocumentVersionList } from "@/components/documents/archive";

function date(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }

export default async function AdminDocumentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const result = await getDocument(id);
  if (!result) return <div className="app-content"><Link className="button button-quiet" href="/admin/documents/files"><ArrowLeft size={14} /> Back to documents</Link><h1>Document not found</h1></div>;
  const { document, rawText, versions, changes, duplicates } = result;
  return <div className="app-content"><Link className="button button-quiet" href="/admin/documents/files"><ArrowLeft size={14} /> Back to documents</Link><div style={{ marginTop: 22, maxWidth: 980 }}><div className="eyebrow">Private source document</div><DocumentNav /><div className="ops-inline" style={{ justifyContent: "space-between" }}><div><h1>{document.title}</h1><p className="app-subtitle">{document.relativePath || "No relative path"}</p></div><span className={document.isMissing ? "badge badge-neutral" : document.isUnavailable ? "badge badge-coral" : "badge badge-mint"}>{document.isMissing ? "missing" : document.isUnavailable ? "unavailable" : "current"}</span></div><section className="surface info-card" style={{ marginTop: 20 }}><h2>Source</h2><dl className="security-details"><div><dt>Relative path</dt><dd><code>{document.relativePath || "—"}</code></dd></div><div><dt>Area</dt><dd>{document.sourceArea || "—"}</dd></div><div><dt>Type</dt><dd>{document.documentType || "—"} · {document.mimeType || "—"}</dd></div><div><dt>Size</dt><dd>{document.fileSizeBytes ?? "—"} bytes</dd></div><div><dt>Filesystem modified</dt><dd>{date(document.filesystemModifiedAt)}</dd></div><div><dt>First seen / last seen</dt><dd>{date(document.firstSeenAt)} / {date(document.lastSeenAt)}</dd></div><div><dt>Last changed</dt><dd>{date(document.lastChangedAt)}</dd></div><div><dt>Current hash</dt><dd><code>{document.contentHash || "—"}</code></dd></div></dl></section><section className="surface info-card" style={{ marginTop: 18 }}><h2>Current extracted version</h2><p className="muted">{document.extractionStatus || "pending"}{document.extractionError ? ` · ${document.extractionError}` : ""}</p><pre style={{ whiteSpace: "pre-wrap", maxHeight: 520, overflow: "auto", fontSize: 12 }}>{rawText || "No extracted text is available for this version."}</pre></section><section className="surface info-card" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Version history</h2><span className="muted">{versions.length}</span></div><DocumentVersionList versions={versions} /></section><section className="surface info-card" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Change history</h2><span className="muted">{changes.length}</span></div><DocumentChangeList changes={changes} /></section><section className="surface info-card" style={{ marginTop: 18 }}><div className="panel-heading"><h2>Exact content duplicates</h2><span className="muted">{duplicates.length}</span></div>{duplicates.map((duplicate) => <Link className="queue-row" href={`/admin/documents/files/${duplicate.id}`} key={duplicate.id}><div><strong>{duplicate.title}</strong><p>{duplicate.relativePath}</p></div><ExternalLink size={14} /> </Link>)}{!duplicates.length && <p className="muted">No other current OneDrive source has this content hash.</p>}</section></div></div>;
}
