import { readPageData, meetingPreview } from "@/lib/local-preview";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { getMeetingDashboard } from "@/lib/db/meetings";
import { MeetingNav } from "@/components/meetings/archive";

export default async function AdminMeetingsPage() {
  const dashboard = await readPageData(() => getMeetingDashboard(), meetingPreview);
  return <div className="app-content"><div className="eyebrow">Admin · meeting archive</div><h1>The meeting<br />memory shelf.</h1><p className="app-subtitle">Meeting logs from Google Docs shared in Slack, alongside historical recordings. Source notes remain unreviewed until explicitly approved.</p><MeetingNav /><div className="metric-grid"><Metric label="Meetings" value={dashboard.counts.meetings} /><Metric label="Notes" value={dashboard.counts.notes} /><Metric label="Transcripts" value={dashboard.counts.transcripts} /><Metric label="Summaries" value={dashboard.counts.summaries} /><Metric label="Changed artifacts" value={dashboard.counts.changedArtifacts} /><Metric label="Run failures" value={dashboard.counts.errors} /></div><div className="app-grid" style={{ marginTop: 24 }}><section className="surface app-panel"><div className="panel-heading"><h2>Meeting sync health</h2><Link href="/admin/meetings/all">Browse meetings <ArrowRight size={12} /></Link></div><dl className="security-details"><div><dt>Latest status</dt><dd>{String(dashboard.latestRun?.status ?? "Not run")}</dd></div><div><dt>Discovered</dt><dd>{dashboard.latestRun?.records_seen ?? 0}</dd></div><div><dt>Created</dt><dd>{dashboard.latestRun?.records_created ?? 0}</dd></div><div><dt>Changed</dt><dd>{dashboard.latestRun?.records_updated ?? 0}</dd></div><div><dt>Errors</dt><dd>{dashboard.latestRun?.records_failed ?? 0}</dd></div></dl></section><aside className="surface-dark app-panel"><div className="eyebrow" style={{ color: "var(--mint)" }}>Privacy boundary</div><h2 style={{ color: "var(--paper)", marginTop: 26, fontSize: 20, fontWeight: 500 }}>Admin-only raw meetings.</h2><p style={{ color: "rgba(247,247,243,.68)", fontSize: 12, lineHeight: 1.5 }}>Meeting notes, transcripts and summaries are not member or public knowledge. Future decisions and actions will require a separate human-review layer.</p></aside></div>{dashboard.latestMeeting && <section style={{ marginTop: 24 }}><div className="eyebrow">Latest meeting</div><div className="surface info-card"><Link href={`/admin/meetings/${dashboard.latestMeeting.id}`}><strong>{dashboard.latestMeeting.title}</strong></Link><p className="muted">{dashboard.latestMeeting.startedAt ? new Date(dashboard.latestMeeting.startedAt).toLocaleString("en-GB") : "Date not provided"}</p></div></section>}<p className="muted" style={{ fontSize: 11, marginTop: 16 }}>Google Docs are read-only at ingestion time. The archive versions artifacts instead of overwriting earlier transcript or summary content.</p></div>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="metric surface"><span>{label}</span><strong>{value}</strong><small>archive records</small></div>; }
